version: '3'

services:
  db:
    image: mariadb:10.3.35
    container_name: mariadb
    hostname: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234qwer
      - MARIADB_USER=test
      - MARIADB_PASSWORD=1234qwer
  es:
    build:
      context: .
      dockerfile: es.Dockerfile
    container_name: es
    hostname: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.17.5
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    depends_on:
      - es
  zookeeper:
    image: zookeeper:3.8.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  redis:
    image: redis:6.2.11
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
